### ISSUE TITLE
Add a "balanced" AI example

### ISSUE THREAD

**Issue by Asuza** [JSJitsu/hero-starter#1]
_hero.js_ contains several examples of various strategies that the player's hero could use. Develop a simple "balanced" strategy to include as an example.

This could be as simple as being an "aggressor" one turn and a "priest" the next. Since it is only an example, it should not be very complex.

**Comment by s-espinosa** [comment]
PR Submitted [here](https://github.com/JSJitsu/hero-starter/pull/6).

**Comment by Asuza** [comment]
Fixed by #6.
