### ISSUE TITLE
Add "--turns" option to allow setting the number of turns for test battles

### ISSUE THREAD

**Issue by Asuza** [JSJitsu/hero-starter#11]
Update the _test-battle.js_ script to have a new "--turns" argument so that the user can specify the number of turns he or she would like the test battle to run for.

**Comment by tenshi13** [comment]
ok weee I saw this first, can I please work on this too? : D

**Comment by tenshi13** [comment]
Hi @Asuza if its cool for me to work on this, I would like to try and incorporate the library Yargs
https://github.com/yargs/yargs
is that ok? Or is it too heavy for the proj?

**Comment by Asuza** [comment]
Feel free to use a library like yargs, @tenshi13. I want to add more options and a help screen later, so that makes sense. I haven't had time yet to investigate if one is better than another, so use your best judgement and we can see how it turns out.

**Comment by Asuza** [comment]
@tenshi13, I just realized that the ai-battle-website is already using a similar library, called [minimist](https://www.npmjs.com/package/minimist), so please use that one so there is consistency. Thanks!

**Comment by tenshi13** [comment]
@Asuza hey man, thanks for the notification, I'll try minimist then, lucky I was too occupied, will update when its done : D

**Comment by tenshi13** [comment]
Hi @Asuza , I've did a PR for this : https://github.com/JSJitsu/hero-starter/pull/12
It works ok, but if user does '--turns a', 'a' as in non integer , it doesnt run... ideally we should handle that and display some message

I had a thought, [yargs](https://github.com/yargs/yargs) might be a better library for cli parameter parsing, as:
- the git repo is very active(last update 2days ago), compared to minimist(last update is aug 2015)
- its got more features, like writing cli descriptions
- it supports more customisation/rule on the cli inputs

just a suggestion, would like to hear what you think?
we can use minimist for now, and then change later also : D

**Comment by Asuza** [comment]
@tenshi13, based on your description, yargs sounds nicer overall. Would you be willing to make a separate PR using yargs? If you can easily add help text using yargs, then that sounds like reason enough to switch to me.

If it looks good, I would like to also implement yargs in the ai-battle-website repo later.

**Comment by tenshi13** [comment]
@Asuza not a prob, I can do that : D 
sry I'll have look slightly later, plz expect a bit of delay

**Comment by tenshi13** [comment]
@Asuza hey man, just a heads up, I was exploring another cli parameter library called [commander.js](https://github.com/tj/commander.js)
- the usage syntax looks more programmer friendly (by a lot, imho...)
- its not as active as yargs, but
- its slightly lighter library, and would have all of what we need i presume

I think I'd prefer to go with commander.js if you're cool with it

tq

**Comment by Asuza** [comment]
Go for it, @tenshi13!

**Comment by tenshi13** [comment]
@Asuza hey man, sorry for the delay, a new PR with the commander.js has been created, https://github.com/JSJitsu/hero-starter/pull/13, please give it a review?

**Comment by Asuza** [comment]
Fixed by #13.
