### ISSUE TITLE
Show whether the player won or lost

### ISSUE THREAD

**Issue by Asuza** [JSJitsu/hero-starter#2]
When running the _test-battle.js_ script, it doesn't show if the player won or lost the game. Inspect the `game` object to determine how to show that information, and add it to the output (after the loop).

**Comment by vikneshwar** [comment]
Hi Asuza , as you told i inspected the `game` object , i don't find any information about the game result ,are you talking about `game.attackMessage` which is always "MyHero stabbed Enemy" . Even i went through `game.heroes` and both the hero objects `won` flag is `false`

**Comment by Asuza** [comment]
Hi @vikneshwar, I believe some games are too short for anyone to win, so it may not always have a winner. Unfortunately, @tlent already submitted a PR for this issue, it just has a conflict right now.

There is also a `winningTeam` property, if I recall.

**Comment by vikneshwar** [comment]
Hi @Asuza no problem , bad i dint check that PR . Thanks :) Would be happy to help you , if there are any issues or enhancements

**Comment by Asuza** [comment]
@vikneshwar I added issue #7, and will try to add more as I have time. Thanks!
