### ISSUE TITLE
Fix linting problems with test-battle.js script

### ISSUE THREAD

**Issue by Asuza** [JSJitsu/hero-starter#3]
The _test-battle.js_ file has several linting issues. From the command line (while in your local _hero-starter_ directory), issue the following command after running `npm install` once:

```
./node_modules/eslint/bin/eslint.js test-battle.js
```

The lint errors shown need to be fixed.

**Comment by GaynullinDima** [comment]
PR'd

**Comment by Asuza** [comment]
Fixed by #4. Thanks, @GaynullinDima!
