### ISSUE TITLE
soycode - error during game run

### ISSUE THREAD

**Issue by Asuza** [JSJitsu/hero-starter#31]
@soycode, please note the following error that occurred during the game today.
```
TypeError: helpers.safetyCheck is not a function
    at Object.helpers.findSafestHealthWell (soycode_helpers.js:205:18)
    at move (soycode_hero.js:191:24)
```
I don't have more information to give you about why it happened. Good luck!

**Comment by agallant** [comment]
Ah, just a helper I failed to copy over from the old version, thanks for the catch - I'm surprised my hero still moved around. Should be fixed now.

**Comment by Asuza** [comment]
Cool, thanks! There's no publicly accessible way to find errors like that from the game replay, so I'll post whatever I find in this repo's Issues as they come up.

**Comment by Asuza** [comment]
@soycode, another error occurred:
```
TypeError: helpers.neighbors is not a function
    at Object.helpers.safetyCheck (soycode_helpers.js:209:29)
    at Object.helpers.findSafestHealthWell (soycode_helpers.js:261:18)
    at move (soycode_hero.js:191:24)
    at soycode:1:12
```

**Comment by agallant** [comment]
Shoulda just copied the old file wholesale I guess... fixed now, and doublechecked that should be all of them.

**Comment by Asuza** [comment]
No problem! I'll re-open if something else crops up.
