### ISSUE TITLE
amacfie - error during game run

### ISSUE THREAD

**Issue by Asuza** [JSJitsu/hero-starter#32]
@amacfie, please note the following errors that occurred during the game today.
```
TypeError: helpers.findTile is not a function
    at moves.custom.balanced (amacfie_hero.js:265:22)
```
```
TypeError: helpers.findTile is not a function
    at moves.custom.balanced (amacfie_hero.js:288:22)
```
```
TypeError: helpers.findTile is not a function
    at moves.custom.balanced (amacfie_hero.js:302:20)
```
I don't have more information to give you about why it happened. Good luck!

**Comment by andrew222651** [comment]
Thanks! Should be fixed by https://github.com/amacfie/hero-starter/commit/b3deee45d4f0f27edc576078d52b03f50dabc7ae

**Comment by Asuza** [comment]
Great! I'll reopen if something pops up in the next game.
