### ISSUE TITLE
Allow the user to step through the battle turn-by-turn

### ISSUE THREAD

**Issue by Asuza** [JSJitsu/hero-starter#7]
Allow the _test-battle.js_ script to be given an argument to pause the game each turn.

The script would run normally (and play all the turns) when not given arguments.

When started like `node test-battle.js --wait`, have the script wait for the user each turn. The output might resemble this:

```
-----
Turn 10:
-----
MyHero tried to move South
MyHero owns 0 diamond mines
MyHero has 100 health
|---|---|---|---|---|
|   |   |   |   |   |
|---|---|---|---|---|
|   |   |   |   |   |
|---|---|---|---|---|
|   |D00|WWW|D01|H00|
|---|---|---|---|---|
|   |   |   |   |   |
|---|---|---|---|---|
|   |   |   |   |H01|
|---|---|---|---|---|
********

Press ENTER to continue...
```

It would be nice if when using the "wait" mode, the previous turn's map would be cleared away, showing only one turn at a time.

**Comment by tenshi13** [comment]
Good day @Asuza, cool project here, mind if I give this a go? :D

**Comment by Asuza** [comment]
By all means, @tenshi13. Go right ahead.

**Comment by tenshi13** [comment]
Hi @Asuza I've did a PR : https://github.com/JSJitsu/hero-starter/pull/10
very sorry I moved the code a lot, 
I was having problem with stdin am not familiar with nodejs, 
is there a better way to do nodejs stdin and stop code from stepping ahead?

**Comment by Asuza** [comment]
Hi @tenshi13! I'm not sure if there is a better way or not, but I might look into it later. When I tested your branch it worked very well. It just needed a couple of changes, which I commented on in your PR.

**Comment by tenshi13** [comment]
Hi @Asuza thx for the comments, glad that you are actually happy with the change,
please expect some delays (I'm @ work : P)
am talking to colleagues about node stdin, very curious if there's easier way to do it

**Comment by tenshi13** [comment]
@Asuza just did an update on https://github.com/JSJitsu/hero-starter/pull/10
can you please review it again

**Comment by Asuza** [comment]
Looks great, @tenshi13! Thanks for the contribution.

**Comment by tenshi13** [comment]
oh wow awesome, glad it's been accepted, thx for the challenge : D
