### ISSUE TITLE
Replace game_logic with ai-battle-engine module

### ISSUE THREAD

**Issue by Asuza** [JSJitsu/hero-starter#8]
Install the [ai-battle-engine repo](https://github.com/JSJitsu/ai-battle-engine) as an npm dependency and replace all code referencing the _game_logic_ folder to instead use the newly-added npm module "ai-battle-engine".

Make sure to remove the _game_logic_ folder when done, run tests with `npm test` and run the linter with `./node_modules/eslint/bin/eslint.js test-battle.js`, and of course, ensure the _test-battle.js_ script functions properly.

**Comment by adnrs96** [comment]
I can try this.
@Asuza If i am correct i have to publish ai-battle-engine repo to npm and modify require statements and package.json file accordingly ?

**Comment by Asuza** [comment]
Hey @adnrs96! You don't have to publish it to npm. You can point _package.json_ to a Git repo and it will work the same. I'd like to avoid publishing to npm at the moment. You're right about the rest of it.

Thanks!

**Comment by adnrs96** [comment]
I didn't knew that could be done. Thanks for letting me know @Asuza .
